parameters:
#    r4f_user.example.class: r4f\UserBundle\Example

services:
#    r4f_user.example:
#        class: %r4f_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
