parameters:
#    r4f_user.example.class: r4f\UserBundle\Example
services:
    acme_user.registration.form.type:
        class: r4f\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: r4f_user_registration }
