courses_list:
    pattern:  /courses/list
    defaults: { _controller: r4fCourseBundle:Course:list }
select_course:
    pattern:  /courses/{id}
    defaults: { _controller: r4fCourseBundle:Course:selectCourse }
    requirements:
        id:   \d+
join_course:
    pattern:  /courses/{id}/join
    defaults: { _controller: r4fCourseBundle:Course:joinCourse }
    requirements:
        id:   \d+
leave_course:
    pattern:  /courses/{id}/leave
    defaults: { _controller: r4fCourseBundle:Course:leaveCourse }
    requirements:
        id:   \d+
create_course:
    pattern:  /courses/new
    defaults: { _controller: r4fCourseBundle:Course:createCourse }


