parameters:
#    r4f_course.example.class: r4f\CourseBundle\Example

services:
#    r4f_course.example:
#        class: %r4f_course.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
